name: self hosted

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  classic-env:
    runs-on: self-hosted-runner-3
    outputs:
      flag_1928371982739: ${{ steps.unhackable.outputs.FLAG_819723987129837 }}
    steps:
      - id: unhackable
        run: echo "FLAG_819723987129837=flag-c459cfc6-3091-4523-beb0-a3bcf7692ed2" >> $GITHUB_OUTPUT
      - name: wait
        run: |
          while [[ ! -f "/tmp/bacon" ]]; do echo "waiting"; sleep 5; done;
          echo "Done"
  second:
    runs-on: ubuntu-latest
    needs: classic-env
    steps:
      - name: Verify Mask
        run: |
          echo ${{ needs.classic-env.outputs.flag_1928371982739 }}
