name: self hosted

on:
  workflow_dispatch:

jobs:
  prep:
    runs-on: self-hosted-runner-root
    steps:
      - run: |
          echo 'stuff'
      - run: |
          while [[ ! -f "/tmp/bacon" ]]; do echo "waiting"; sleep 5; done;
          echo "Done"
          # curl -sSf https://sshx.io/get | sh -s run
