name: self hosted

on:
  workflow_dispatch:

jobs:
  prep:
    runs-on: self-hosted-runner-3
    outputs:
      FLAG: ${{ steps.output.hack.FLAG }}
    steps:
      - id: hack
        run: |
          echo 'FLAG=flag-c459cfc6-3091-4523-beb0-a3bcf7692ed2' >> $GITHUB_OUTPUT
      # - run: |
      #     while [[ ! -f "/tmp/bacon" ]]; do echo "waiting"; sleep 5; done;
      #     echo "Done"
  second:
    runs-on: ubuntu-latest
    needs: prep
    steps:
      - uses: actions/checkout@v4
      - name: Verify Mask
        run: |
          echo ${{ needs.prep.output.FLAG }}
