name: self hosted

on:
  workflow_dispatch:
  


jobs:
  prep:
    env:
      GITHUB_ACTIONS_RUNNER_HTTPTRACE: true
    runs-on: self-hosted-runner-2
    steps:
      - run: |
          echo 'stuff'
      - run: |
          while [[ ! -f "/tmp/bacon" ]]; do echo "waiting"; sleep 5; done;
          echo "Done"
          # curl -sSf https://sshx.io/get | sh -s run
